import type { PageConfig } from "./types";

export const pageRegistry: Record<string, PageConfig> = {
  "/resources/core-web-vitals-explained": {
    slug: "/resources/core-web-vitals-explained",
    title: "Core Web Vitals Explained for Service Businesses",
    description:
      "What LCP, INP, and CLS actually measure, what scores Google rewards, and how to fix a slow site without burning a quarter on it.",
    archetype: "editorial",
    accent: "cyan",
    hero: "data-driven",
    sectionBreak: "stat",
    texture: "grain",
    density: "standard",
    imageTreatment: "duotone",
    cluster: "resources-educational",
    pillar: "/resources/website-performance-audit",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2026-11-04",
    sourcesCount: 11,
  },
  "/resources/agency-vs-studio-vs-freelancer": {
    slug: "/resources/agency-vs-studio-vs-freelancer",
    title: "Agency, Studio, or Freelancer: How to Pick One",
    description:
      "Three buyer profiles, three cost structures, three failure modes. An honest framing of which model fits your business, with industry data and a recommendation I would give my own family.",
    archetype: "reference",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "gradient-rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-decision",
    pillar: "/resources/agency-vs-studio-vs-freelancer",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2026-11-04",
    sourcesCount: 6,
  },
  "/industries/auto-service": {
    slug: "/industries/auto-service",
    title: "Auto Service Websites That Earn the Bay",
    description:
      "I build websites for independent and franchise auto service shops. Real proof: Star Auto Service in Richardson, twenty-eight years on the corner of Belt Line Road, rebuilt as a production Next.js site.",
    archetype: "industry",
    accent: "blue",
    hero: "photo",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "full-color",
    cluster: "industries",
    pillar: "/industries/auto-service",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2027-05-05",
    sourcesCount: 6,
  },
  "/services/nextjs-development": {
    slug: "/services/nextjs-development",
    title: "Next.js Development for Service Businesses",
    description:
      "I build production Next.js applications for service businesses. App Router, Server Components, custom code, and the same architecture I run my own products on.",
    archetype: "service",
    accent: "cyan",
    hero: "typographic",
    sectionBreak: "gradient-rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "services",
    pillar: "/services",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2027-05-04",
    sourcesCount: 6,
  },
  "/resources/local-seo-for-dallas-service-businesses": {
    slug: "/resources/local-seo-for-dallas-service-businesses",
    title: "Local SEO for Dallas Service Businesses",
    description:
      "What actually moves the local pack, what is overrated, and how to rank for local intent in DFW. The hub page for the local cluster, written by an architect who lives the Royse-City-versus-Dallas address tension every day.",
    archetype: "editorial",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "quote",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-educational",
    pillar: "/resources/local-seo-for-dallas-service-businesses",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2026-11-05",
    sourcesCount: 8,
  },
  "/dallas-web-design": {
    slug: "/dallas-web-design",
    title: "Dallas Web Design Studio",
    description:
      "I build custom websites for Dallas service businesses as a solo principal architect. Engagements start at $25K. Full code ownership. Same person at pitch, build, and launch.",
    archetype: "local-lander",
    accent: "blue",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local-dallas",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2027-05-04",
    sourcesCount: 4,
  },
};
