import type { PageConfig } from "./types";

export const pageRegistry: Record<string, PageConfig> = {
  "/resources/core-web-vitals-explained": {
    slug: "/resources/core-web-vitals-explained",
    title: "Core Web Vitals Explained for Service Businesses",
    description:
      "What LCP, INP, and CLS actually measure, what scores Google rewards, and how to fix a slow site without burning a quarter on it.",
    archetype: "editorial",
    accent: "cyan",
    hero: "data-driven",
    sectionBreak: "stat",
    texture: "grain",
    density: "standard",
    imageTreatment: "duotone",
    cluster: "resources-educational",
    pillar: "/resources/website-performance-audit",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2026-11-04",
    sourcesCount: 11,
  },
  "/resources/what-a-website-should-cost": {
    slug: "/resources/what-a-website-should-cost",
    title: "What a Website Should Cost in 2026",
    description:
      "Honest ranges by tier, what drives cost up, what is worth paying for, and what is not. Anchored to my published prices and real industry data, not to a sales pitch.",
    archetype: "reference",
    accent: "blue",
    hero: "typographic",
    sectionBreak: "stat",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-decision",
    pillar: "/resources/agency-vs-studio-vs-freelancer",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2026-11-05",
    sourcesCount: 6,
  },
  "/resources/redesign-vs-rebuild": {
    slug: "/resources/redesign-vs-rebuild",
    title: "Redesign vs Rebuild: Which One Your Site Actually Needs",
    description:
      "Honest framing on when a redesign is the right move and when it is just lipstick on compounding technical debt. Anchored on engineering economics, not on vendor pitches.",
    archetype: "reference",
    accent: "cyan",
    hero: "typographic",
    sectionBreak: "quote",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-decision",
    pillar: "/resources/agency-vs-studio-vs-freelancer",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 7,
  },
  "/services/website-rebuild": {
    slug: "/services/website-rebuild",
    title: "Website Rebuild: Methodology and How I Protect What Already Works",
    description:
      "What a real rebuild engagement looks like, how I protect existing organic and conversion signal through the migration, and the three-tier path from a Pathlight scan to a shipped rebuild. The companion service page to the redesign-vs-rebuild decision guide.",
    archetype: "service",
    accent: "blue",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "services",
    pillar: "/services",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 6,
  },
  "/resources/agency-vs-studio-vs-freelancer": {
    slug: "/resources/agency-vs-studio-vs-freelancer",
    title: "Agency, Studio, or Freelancer: How to Pick One",
    description:
      "Three buyer profiles, three cost structures, three failure modes. An honest framing of which model fits your business, with industry data and a recommendation I would give my own family.",
    archetype: "reference",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "gradient-rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-decision",
    pillar: "/resources/agency-vs-studio-vs-freelancer",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2026-11-04",
    sourcesCount: 6,
  },
  "/industries/medical-and-dental": {
    slug: "/industries/medical-and-dental",
    title: "Medical and Dental Practice Websites That Earn the Chair",
    description:
      "Healthcare buyers are anxious, risk-averse, and search-driven. The site that converts is the one that answers the appointment question in ninety seconds and treats HIPAA seriously. Anchored on the Ridgeview dental design brief.",
    archetype: "industry",
    accent: "cyan",
    hero: "photo",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "full-color",
    cluster: "industries",
    pillar: "/industries/medical-and-dental",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2027-05-05",
    sourcesCount: 6,
  },
  "/industries/trades-and-hvac": {
    slug: "/industries/trades-and-hvac",
    title: "Trades and HVAC Websites That Fill the Dispatch Board",
    description:
      "When the AC dies on a 105-degree afternoon, a homeowner picks the contractor who answers the phone fastest, has a license number visible, and looks like a real business. The site that fills the dispatch board treats urgency as the dominant design driver.",
    archetype: "industry",
    accent: "amber",
    hero: "photo",
    sectionBreak: "stat",
    texture: "clean",
    density: "standard",
    imageTreatment: "full-color",
    cluster: "industries",
    pillar: "/industries/trades-and-hvac",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2027-05-06",
    sourcesCount: 6,
  },
  "/industries/legal": {
    slug: "/industries/legal",
    title: "Legal Practice Websites That Sign the Case",
    description:
      "Legal buyers are skeptical, time-pressured, and operating under search-driven trust signals. The site that converts treats State Bar advertising rules as a feature, not an afterthought, and answers the case-fit question in ninety seconds. Anchored on the personal injury law design brief.",
    archetype: "industry",
    accent: "violet",
    hero: "photo",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "full-color",
    cluster: "industries",
    pillar: "/industries/legal",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2027-05-06",
    sourcesCount: 6,
  },
  "/industries/auto-service": {
    slug: "/industries/auto-service",
    title: "Auto Service Websites That Earn the Bay",
    description:
      "I build websites for independent and franchise auto service shops. Real proof: Star Auto Service in Richardson, twenty-eight years on the corner of Belt Line Road, rebuilt as a production Next.js site.",
    archetype: "industry",
    accent: "blue",
    hero: "photo",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "full-color",
    cluster: "industries",
    pillar: "/industries/auto-service",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2027-05-05",
    sourcesCount: 6,
  },
  "/services/website-performance-audit": {
    slug: "/services/website-performance-audit",
    title: "Website Performance Audit: Methodology and What Tools Miss",
    description:
      "What a real performance audit covers, what free tools quietly miss, and the three-tier path from a Pathlight scan to shipped fixes. The educational counterpart to the Fix Sprint productized tier.",
    archetype: "service",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "stat",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "services",
    pillar: "/services",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2026-11-05",
    sourcesCount: 7,
  },
  "/services/nextjs-development": {
    slug: "/services/nextjs-development",
    title: "Next.js Development for Service Businesses",
    description:
      "I build production Next.js applications for service businesses. App Router, Server Components, custom code, and the same architecture I run my own products on.",
    archetype: "service",
    accent: "cyan",
    hero: "typographic",
    sectionBreak: "gradient-rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "services",
    pillar: "/services",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2027-05-04",
    sourcesCount: 6,
  },
  "/resources/local-seo-for-dallas-service-businesses": {
    slug: "/resources/local-seo-for-dallas-service-businesses",
    title: "Local SEO for Dallas Service Businesses",
    description:
      "What actually moves the local pack, what is overrated, and how to rank for local intent in DFW. The hub page for the local cluster, written by an architect who lives the Royse-City-versus-Dallas address tension every day.",
    archetype: "editorial",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "quote",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "resources-educational",
    pillar: "/resources/local-seo-for-dallas-service-businesses",
    lastReviewed: "2026-05-05",
    nextReviewDue: "2026-11-05",
    sourcesCount: 8,
  },
  "/plano-web-design": {
    slug: "/plano-web-design",
    title: "Plano Web Design Studio",
    description:
      "I build custom websites for Plano businesses. Solo principal architect, full code ownership, no agency coordination layer. Anchored on the Legacy West corporate corridor and the Plano service-business buyer profile.",
    archetype: "local-lander",
    accent: "cyan",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/frisco-web-design": {
    slug: "/frisco-web-design",
    title: "Frisco Web Design Studio",
    description:
      "I build custom websites for Frisco businesses. The fastest-growing major suburb in DFW, the home of Sports City USA, and a buyer base that expects polish equal to The Star. This page covers what that means for a real engagement.",
    archetype: "local-lander",
    accent: "amber",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/mckinney-web-design": {
    slug: "/mckinney-web-design",
    title: "McKinney Web Design Studio",
    description:
      "I build custom websites for McKinney businesses. Collin County seat, historic downtown square, diversifying corporate base. A different buyer than Plano or Frisco, with a stronger preference for craft over scale.",
    archetype: "local-lander",
    accent: "violet",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/allen-web-design": {
    slug: "/allen-web-design",
    title: "Allen Web Design Studio",
    description:
      "I build custom websites for Allen businesses. Established corporate-corridor city, top-decile schools, and a service-business buyer base shaped by The Watters Creek lifestyle center and a long mature growth pattern.",
    archetype: "local-lander",
    accent: "blue",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/richardson-web-design": {
    slug: "/richardson-web-design",
    title: "Richardson Web Design Studio",
    description:
      "I build custom websites for Richardson businesses. The original DFW Telecom Corridor, a deep tech and professional services population, and a buyer base that knows the difference between marketing and engineering.",
    archetype: "local-lander",
    accent: "cyan",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/prosper-web-design": {
    slug: "/prosper-web-design",
    title: "Prosper Web Design Studio",
    description:
      "I build custom websites for Prosper businesses. The fastest-growing exclusivity-focused suburb in DFW, a buyer base that more than doubled in a decade, and the high-end residential service economy that comes with master-planned-community demographics.",
    archetype: "local-lander",
    accent: "amber",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-06",
    nextReviewDue: "2026-11-06",
    sourcesCount: 4,
  },
  "/dallas-web-design": {
    slug: "/dallas-web-design",
    title: "Dallas Web Design Studio",
    description:
      "I build custom websites for Dallas service businesses as a solo principal architect. Engagements start at $25K. Full code ownership. Same person at pitch, build, and launch.",
    archetype: "local-lander",
    accent: "blue",
    hero: "typographic",
    sectionBreak: "rule",
    texture: "clean",
    density: "standard",
    imageTreatment: "none",
    cluster: "local-dallas",
    pillar: "/dallas-web-design",
    lastReviewed: "2026-05-04",
    nextReviewDue: "2027-05-04",
    sourcesCount: 4,
  },
};
